FROM fedora:latest 
RUN dnf update -y
RUN dnf group -y install development-tools
RUN dnf install -y wget
RUN wget -q -O gpg.key https://rpm.grafana.com/gpg.key
RUN rpm --import gpg.key
RUN dnf install -y vim
COPY grafana.repo /etc/yum.repos.d
RUN dnf install -y grafana
WORKDIR /usr/share/grafana
ENTRYPOINT ["/usr/share/grafana/bin/grafana","server"]


